// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rncwebview.djinni

#pragma once

#include <memory>
#include <string>

namespace RNCWebView {

/**
 * webview_event = record {
 *   id: i32;
 *   url: string;
 *   loading: bool;
 *   title: string;
 *   canGoBack: bool;
 *   canGoForward: bool;
 * }
 */
class WebviewLifecycle {
public:
    virtual ~WebviewLifecycle() {}

    static std::shared_ptr<WebviewLifecycle> create();

    /** onShouldStartLoadWithRequest(event: webview_event, url: string): bool; */
    virtual bool onShouldStartLoadWithRequest(const std::string & url) = 0;
};

}  // namespace RNCWebView
