// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rncwebview.djinni

#include "NativeWebviewLifecycle.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeWebviewLifecycle::NativeWebviewLifecycle() : ::djinni::JniInterface<::RNCWebView::WebviewLifecycle, NativeWebviewLifecycle>("com/reactnativecommunity/webview/WebviewLifecycle$CppProxy") {}

NativeWebviewLifecycle::~NativeWebviewLifecycle() = default;


CJNIEXPORT void JNICALL Java_com_reactnativecommunity_webview_WebviewLifecycle_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::RNCWebView::WebviewLifecycle>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_reactnativecommunity_webview_WebviewLifecycle_00024CppProxy_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::RNCWebView::WebviewLifecycle::create();
        return ::djinni::release(::djinni_generated::NativeWebviewLifecycle::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_reactnativecommunity_webview_WebviewLifecycle_00024CppProxy_native_1onShouldStartLoadWithRequest(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_url)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNCWebView::WebviewLifecycle>(nativeRef);
        auto r = ref->onShouldStartLoadWithRequest(::djinni::String::toCpp(jniEnv, j_url));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
