// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rncwebview.djinni

#pragma once

#include "djinni_support.hpp"
#include "webview_lifecycle.hpp"

namespace djinni_generated {

class NativeWebviewLifecycle final : ::djinni::JniInterface<::RNCWebView::WebviewLifecycle, NativeWebviewLifecycle> {
public:
    using CppType = std::shared_ptr<::RNCWebView::WebviewLifecycle>;
    using CppOptType = std::shared_ptr<::RNCWebView::WebviewLifecycle>;
    using JniType = jobject;

    using Boxed = NativeWebviewLifecycle;

    ~NativeWebviewLifecycle();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeWebviewLifecycle>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeWebviewLifecycle>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeWebviewLifecycle();
    friend ::djinni::JniClass<NativeWebviewLifecycle>;
    friend ::djinni::JniInterface<::RNCWebView::WebviewLifecycle, NativeWebviewLifecycle>;

};

}  // namespace djinni_generated
